In [10]:
import numpy as np

# Numpy Arrays
## Numpy Arrays are similar to Python Lists but with some differences:
- Numpy arrays are homogeneous (all elements are of the same type)
- Numpy arrays are faster and more memory efficient
- Numpy arrays are optimized for numerical operations
- Numpy arrays can be multi-dimensional

In [11]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
my_array = np.array(l)  # convert list to numpy array (ndarray)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
list_rand = [1, 2.5, 'YES', True]
np.array(list_rand)  # all elements are converted to string
for i in np.array(list_rand):
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [14]:
my_array.dtype

dtype('int32')

# Numpy Array (element-wise operations / vectorization)
- In Numpy, operations are performed element-wise
- In Numpy we have many functions that can be applied to the entire array, is perfect for numerical operations


In [15]:
l = [2, 4, 6, 8]
array_list = np.arange(2, 10, 2)    # same as range() but returns ndarray

In [16]:
l * 2   

[2, 4, 6, 8, 2, 4, 6, 8]

In [17]:
array_list * 2

array([ 4,  8, 12, 16])

In [18]:
l + 2   # in list not possible

TypeError: can only concatenate list (not "int") to list

In [ ]:
array_list + 2  # in ndarray possible to add scalar to each element

In [19]:
np.sqrt(array_list)  # element-wise square root


array([1.41421356, 2.        , 2.44948974, 2.82842712])

In [20]:
np.exp(array_list)  # element-wise exponential

array([   7.3890561 ,   54.59815003,  403.42879349, 2980.95798704])

In [21]:
np.log(array_list)  # element-wise natural logarithm

array([0.69314718, 1.38629436, 1.79175947, 2.07944154])

In [22]:
np.sin(array_list)  # element-wise sine

array([ 0.90929743, -0.7568025 , -0.2794155 ,  0.98935825])

# Numpy Array Indexing and Slicing
- Numpy arrays can be indexed and sliced like Python lists


In [23]:
array_list

array([2, 4, 6, 8])

In [24]:
array_list[0]

2

In [25]:
array_list[-1]

8

In [26]:
array_list[0] = 100
array_list

array([100,   4,   6,   8])

In [27]:
array_list[1:3] = 99    # in numpy can assign a value to a slice
array_list  # in numpy changes the original array, not a copy

array([100,  99,  99,   8])

In [28]:
l[1:3] = 99    # in list not possible

TypeError: can only assign an iterable

# Numpy array (Shape and multiple dimensions)

In [29]:
array_list.shape   #  we have only one dimension (4 rows)

(4,)

In [30]:
array_list

array([100,  99,  99,   8])

In [31]:
array_list = array_list.reshape(2, 2)   # reshape to 2 rows and 2 columns
array_list

array([[100,  99],
       [ 99,   8]])

In [32]:
array_list.shape    # We have 2 dimensions (2 rows and 2 columns)

(2, 2)

In [33]:
b = np.arange(1, 101).reshape(25, 4)  # reshape to 25 rows and 4 columns
b

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

# Numpy Array (Indexing and Slicing in multiple dimensions)
## Indexarea in multiple dimensions este similara cu indexarea in liste de liste

In [34]:
a = np.arange(1, 13).reshape(3, 4, order='C')  # order='F' column-major order
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
a = np.arange(1, 13).reshape(3, 4, order='F')  # order='F' column-major order
a

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [39]:
a[1][1]

5

In [40]:
a[0][:]  # first row (all columns)

array([ 1,  4,  7, 10])

In [41]:
a.transpose()  # switch rows with columns

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
a.sum() # sum of all elements

78

In [43]:
a.sum(axis=0)  # sum of each column

array([ 6, 15, 24, 33])

In [44]:
a.sum(axis=1)  # sum of each row

array([22, 26, 30])

# Numpy Array (Boolean Indexing)

In [45]:
mask1 = a > 5
mask1

array([[False, False,  True,  True],
       [False, False,  True,  True],
       [False,  True,  True,  True]])

In [46]:
mask2 = (a > 5) & (a < 10)   # element-wise check if greater 5 and smaller 8 ( Logical and)
mask2

array([[False, False,  True, False],
       [False, False,  True, False],
       [False,  True,  True, False]])

In [47]:
mask3 = (a> 5) | (a < 10)   # element-wise check if greater 5 or smaller 8 ( Logical or)
mask4 = ~mask3  # element-wise negation (Logical not, opposite of mask3)

We can use [] to filter the array based on a boolean mask or a condition

In [49]:
a[a>5]  # use [] and a boolean filter

array([ 7, 10,  8, 11,  6,  9, 12])

In [51]:
a[mask1]    # use [] and a boolean mask

array([ 7, 10,  8, 11,  6,  9, 12])